language: cpp
sudo: required

os:
        - linux
compiler:
        - clang

before_install:
        - sudo apt-get update
        - sudo apt-get install build-essential libcurl4-gnutls-dev clang

script:
        - make
