language: cpp
sudo: required

os:
        - linux
dist: trusty
compiler:
        - g++
install: export CXX="g++-5"
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
script:
        - make

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install build-essential libcurl4-gnutls-dev curl
notifactions:
        on_success: never
        on_failure: always
