language: cpp
sudo: required

os:
        - linux
compiler:
        - g++

before_install:
        - sudo apt-get update
        - sudo apt-get install build-essential libcurl4-gnutls-dev

script:
        - make
