language: cpp
sudo: required

os:
        - linux
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-5
            - gcc-5
script:
        - make
compiler:
        - g++

before_install:
        - sudo apt-get update
        - sudo apt-get install build-essential libcurl4-gnutls-dev g++

script:
        - make
